import type { GodRaysConfig } from "./godrays";

export interface RaysPreset {
  key: string;
  label: string;
  thumb: string;
  config: Partial<GodRaysConfig>;
}

export const PRESETS: RaysPreset[] = [
  {
    key: "sunset",
    label: "Sunset",
    thumb: "linear-gradient(180deg,#ff7b3a,#3a1a4f)",
    config: {
      colorStart: "#ffb46a",
      colorEnd: "#ff5b7f",
      bgType: "gradient",
      bgColor: "#3a1a4f",
      bgColor2: "#ff7b3a",
      bgGradientAngle: 180,
      direction: 200,
      spread: 50,
      originX: 50,
      originY: 100,
      rayCount: 28,
      rayWidth: 70,
      divergence: 1.4,
      opacity: 0.55,
      blur: 12,
      halo: 0.8,
      haloSize: 0.35,
      noise: 6,
      blendMode: "lighter",
    },
  },
  {
    key: "forest",
    label: "Forest light",
    thumb: "linear-gradient(180deg,#0a2a18,#a3d977)",
    config: {
      colorStart: "#cfe88a",
      colorEnd: "#cfe88a",
      bgType: "gradient",
      bgColor: "#06190f",
      bgColor2: "#1c4a26",
      bgGradientAngle: 180,
      direction: 195,
      spread: 35,
      originX: 60,
      originY: -10,
      rayCount: 22,
      rayWidth: 50,
      divergence: 1.8,
      opacity: 0.5,
      blur: 18,
      halo: 0.4,
      haloSize: 0.3,
      noise: 14,
      blendMode: "screen",
    },
  },
  {
    key: "cyber",
    label: "Cyber",
    thumb: "linear-gradient(180deg,#0a0530,#ff2bd6)",
    config: {
      colorStart: "#ff2bd6",
      colorEnd: "#3a8bff",
      bgType: "gradient",
      bgColor: "#070025",
      bgColor2: "#1d0050",
      bgGradientAngle: 200,
      direction: 180,
      spread: 80,
      originX: 50,
      originY: 0,
      rayCount: 60,
      rayWidth: 30,
      divergence: 2.4,
      opacity: 0.4,
      blur: 6,
      halo: 0.6,
      haloSize: 0.18,
      noise: 4,
      blendMode: "lighter",
      fadeToTransparent: true,
    },
  },
  {
    key: "soft",
    label: "Soft mist",
    thumb: "linear-gradient(180deg,#dde8ff,#9aa9c9)",
    config: {
      colorStart: "#ffffff",
      colorEnd: "#ffffff",
      bgType: "gradient",
      bgColor: "#9aa9c9",
      bgColor2: "#dde8ff",
      bgGradientAngle: 180,
      direction: 210,
      spread: 30,
      originX: 30,
      originY: -10,
      rayCount: 18,
      rayWidth: 90,
      divergence: 1.2,
      opacity: 0.35,
      blur: 30,
      halo: 0.3,
      haloSize: 0.4,
      noise: 6,
      blendMode: "screen",
    },
  },
  {
    key: "stage",
    label: "Stage",
    thumb: "linear-gradient(180deg,#000,#5b3aff)",
    config: {
      colorStart: "#a17bff",
      colorEnd: "#a17bff",
      bgType: "gradient",
      bgColor: "#000000",
      bgColor2: "#1a0040",
      bgGradientAngle: 180,
      direction: 180,
      spread: 70,
      originX: 50,
      originY: -5,
      rayCount: 14,
      rayWidth: 110,
      divergence: 2.2,
      opacity: 0.45,
      blur: 4,
      halo: 0.5,
      haloSize: 0.2,
      noise: 12,
      blendMode: "lighter",
      randomness: 10,
    },
  },
  {
    key: "neon",
    label: "Neon burst",
    thumb: "linear-gradient(180deg,#001028,#00f5d4)",
    config: {
      colorStart: "#00f5d4",
      colorEnd: "#7b61ff",
      bgType: "solid",
      bgColor: "#001028",
      direction: 90,
      spread: 360,
      originX: 50,
      originY: 50,
      rayCount: 80,
      rayWidth: 14,
      divergence: 6,
      opacity: 0.5,
      blur: 4,
      halo: 0.7,
      haloSize: 0.15,
      noise: 6,
      blendMode: "lighter",
    },
  },
];
