import type { GodRaysConfig } from "./godrays";

export type PresetCategory = "color" | "rays";

export interface RaysPreset {
  key: string;
  label: string;
  thumb: string;
  category: PresetCategory;
  config: Partial<GodRaysConfig>;
}

// Color-only presets — only affect background + ray colors, never shape
export const COLOR_PRESETS: RaysPreset[] = [
  {
    key: "c_contentnow",
    label: "ContentNow",
    thumb: "linear-gradient(160deg,#0d0200,#D1DD10)",
    category: "color",
    config: {
      colorStart: "#D1DD10",
      colorEnd: "#54580a",
      haloColor: "#D1DD10",
      bgType: "solid",
      bgColor: "#121212",
    },
  },
  {
    key: "c_ember",
    label: "Ember",
    thumb: "linear-gradient(160deg,#0d0200,#ff4400)",
    category: "color",
    config: {
      colorStart: "#ff6a00",
      colorEnd: "#ff2200",
      haloColor: "#ff4400",
      bgType: "solid",
      bgColor: "#0d0200",
    },
  },
  {
    key: "c_golden",
    label: "Golden hour",
    thumb: "linear-gradient(160deg,#0b1024,#ffd28a)",
    category: "color",
    config: {
      colorStart: "#ffe58a",
      colorEnd: "#ffd28a",
      haloColor: "#ffd28a",
      bgType: "gradient",
      bgColor: "#0b1024",
      bgColor2: "#1a1340",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_sunset",
    label: "Sunset",
    thumb: "linear-gradient(160deg,#3a1a4f,#ff7b3a)",
    category: "color",
    config: {
      colorStart: "#ffb46a",
      colorEnd: "#ff5b7f",
      haloColor: "#ffb46a",
      bgType: "gradient",
      bgColor: "#3a1a4f",
      bgColor2: "#ff7b3a",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_cyber",
    label: "Cyber",
    thumb: "linear-gradient(160deg,#070025,#ff2bd6)",
    category: "color",
    config: {
      colorStart: "#ff2bd6",
      colorEnd: "#3a8bff",
      haloColor: "#ff2bd6",
      bgType: "gradient",
      bgColor: "#070025",
      bgColor2: "#1d0050",
      bgGradientAngle: 200,
    },
  },
  {
    key: "c_forest",
    label: "Forest",
    thumb: "linear-gradient(160deg,#06190f,#a3d977)",
    category: "color",
    config: {
      colorStart: "#cfe88a",
      colorEnd: "#cfe88a",
      haloColor: "#cfe88a",
      bgType: "gradient",
      bgColor: "#06190f",
      bgColor2: "#1c4a26",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_ocean",
    label: "Ocean",
    thumb: "linear-gradient(160deg,#000d1a,#00a8c8)",
    category: "color",
    config: {
      colorStart: "#00d4ff",
      colorEnd: "#80c8ff",
      haloColor: "#00d4ff",
      bgType: "gradient",
      bgColor: "#000d1a",
      bgColor2: "#00131f",
      bgGradientAngle: 180,
    },
  },

  {
    key: "c_dawn",
    label: "Dawn",
    thumb: "linear-gradient(160deg,#1a0a2e,#f7b5d5)",
    category: "color",
    config: {
      colorStart: "#ffd6ec",
      colorEnd: "#c084fc",
      haloColor: "#ffd6ec",
      bgType: "gradient",
      bgColor: "#1a0a2e",
      bgColor2: "#4a1a5e",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_ice",
    label: "Ice",
    thumb: "linear-gradient(160deg,#0a1628,#a8d8f0)",
    category: "color",
    config: {
      colorStart: "#c8eaff",
      colorEnd: "#80c8ff",
      haloColor: "#c8eaff",
      bgType: "gradient",
      bgColor: "#0a1628",
      bgColor2: "#0d2a44",
      bgGradientAngle: 200,
    },
  },
  {
    key: "c_neon",
    label: "Neon",
    thumb: "linear-gradient(160deg,#001028,#00f5d4)",
    category: "color",
    config: {
      colorStart: "#00f5d4",
      colorEnd: "#7b61ff",
      haloColor: "#00f5d4",
      bgType: "solid",
      bgColor: "#001028",
    },
  },
  {
    key: "c_synthwave",
    label: "Synthwave",
    thumb: "linear-gradient(160deg,#0a0018,#ff00cc)",
    category: "color",
    config: {
      colorStart: "#ff00cc",
      colorEnd: "#3300ff",
      haloColor: "#ff00cc",
      bgType: "gradient",
      bgColor: "#0a0018",
      bgColor2: "#1a003a",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_stage",
    label: "Stage",
    thumb: "linear-gradient(160deg,#000,#5b3aff)",
    category: "color",
    config: {
      colorStart: "#a17bff",
      colorEnd: "#a17bff",
      haloColor: "#a17bff",
      bgType: "gradient",
      bgColor: "#000000",
      bgColor2: "#1a0040",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_soft",
    label: "Mist",
    thumb: "linear-gradient(160deg,#9aa9c9,#dde8ff)",
    category: "color",
    config: {
      colorStart: "#ffffff",
      colorEnd: "#ffffff",
      haloColor: "#e0eaff",
      bgType: "gradient",
      bgColor: "#9aa9c9",
      bgColor2: "#dde8ff",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_crimson",
    label: "Crimson",
    thumb: "linear-gradient(160deg,#1a0008,#e8003d)",
    category: "color",
    config: {
      colorStart: "#ff2255",
      colorEnd: "#cc0033",
      haloColor: "#ff2255",
      bgType: "gradient",
      bgColor: "#1a0008",
      bgColor2: "#3a0015",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_volcanic",
    label: "Volcanic",
    thumb: "linear-gradient(160deg,#0d0500,#ff6600)",
    category: "color",
    config: {
      colorStart: "#ff8800",
      colorEnd: "#ff3300",
      haloColor: "#ff5500",
      bgType: "gradient",
      bgColor: "#0d0500",
      bgColor2: "#1a0a00",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_midnight",
    label: "Midnight",
    thumb: "linear-gradient(160deg,#00020f,#1a3aff)",
    category: "color",
    config: {
      colorStart: "#4466ff",
      colorEnd: "#aabbff",
      haloColor: "#4466ff",
      bgType: "gradient",
      bgColor: "#00020f",
      bgColor2: "#000828",
      bgGradientAngle: 200,
    },
  },
  {
    key: "c_rosegold",
    label: "Rose Gold",
    thumb: "linear-gradient(160deg,#1a0810,#ffb3c6)",
    category: "color",
    config: {
      colorStart: "#ffccd5",
      colorEnd: "#e8a090",
      haloColor: "#ffb3c6",
      bgType: "gradient",
      bgColor: "#1a0810",
      bgColor2: "#3a1020",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_toxic",
    label: "Toxic",
    thumb: "linear-gradient(160deg,#030d00,#7fff00)",
    category: "color",
    config: {
      colorStart: "#aaff00",
      colorEnd: "#55cc00",
      haloColor: "#aaff00",
      bgType: "gradient",
      bgColor: "#030d00",
      bgColor2: "#0a1f00",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_copper",
    label: "Copper",
    thumb: "linear-gradient(160deg,#0f0800,#c87941)",
    category: "color",
    config: {
      colorStart: "#e8a060",
      colorEnd: "#c87941",
      haloColor: "#d48840",
      bgType: "gradient",
      bgColor: "#0f0800",
      bgColor2: "#1e1000",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_violet",
    label: "Violet Storm",
    thumb: "linear-gradient(160deg,#08001a,#9900ff)",
    category: "color",
    config: {
      colorStart: "#cc44ff",
      colorEnd: "#6600cc",
      haloColor: "#aa22ff",
      bgType: "gradient",
      bgColor: "#08001a",
      bgColor2: "#180033",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_sakura",
    label: "Sakura",
    thumb: "linear-gradient(160deg,#1a0a12,#ffaad4)",
    category: "color",
    config: {
      colorStart: "#ffd6e8",
      colorEnd: "#ff88bb",
      haloColor: "#ffaad4",
      bgType: "gradient",
      bgColor: "#1a0a12",
      bgColor2: "#2a1020",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_desert",
    label: "Desert",
    thumb: "linear-gradient(160deg,#120900,#e8b560)",
    category: "color",
    config: {
      colorStart: "#f5d080",
      colorEnd: "#e8a040",
      haloColor: "#f0c060",
      bgType: "gradient",
      bgColor: "#120900",
      bgColor2: "#241500",
      bgGradientAngle: 160,
    },
  },
  {
    key: "c_deepsea",
    label: "Deep Sea",
    thumb: "linear-gradient(160deg,#000810,#006680)",
    category: "color",
    config: {
      colorStart: "#00cccc",
      colorEnd: "#0088aa",
      haloColor: "#00bbbb",
      bgType: "gradient",
      bgColor: "#000810",
      bgColor2: "#001520",
      bgGradientAngle: 190,
    },
  },
  {
    key: "c_aurora",
    label: "Aurora",
    thumb: "linear-gradient(160deg,#000d0a,#00ffaa)",
    category: "color",
    config: {
      colorStart: "#00ffcc",
      colorEnd: "#aa44ff",
      haloColor: "#00ddaa",
      bgType: "gradient",
      bgColor: "#000d0a",
      bgColor2: "#001a14",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_blood",
    label: "Blood Moon",
    thumb: "linear-gradient(160deg,#0a0000,#aa2200)",
    category: "color",
    config: {
      colorStart: "#cc3300",
      colorEnd: "#880000",
      haloColor: "#aa2200",
      bgType: "solid",
      bgColor: "#0a0000",
    },
  },
  {
    key: "c_plasma",
    label: "Plasma",
    thumb: "linear-gradient(160deg,#050010,#ff44aa)",
    category: "color",
    config: {
      colorStart: "#ff66cc",
      colorEnd: "#4400ff",
      haloColor: "#ff44aa",
      bgType: "gradient",
      bgColor: "#050010",
      bgColor2: "#0f0028",
      bgGradientAngle: 220,
    },
  },
  {
    key: "c_arctic",
    label: "Arctic",
    thumb: "linear-gradient(160deg,#030810,#88ccff)",
    category: "color",
    config: {
      colorStart: "#cceeff",
      colorEnd: "#88ccff",
      haloColor: "#aaddff",
      bgType: "gradient",
      bgColor: "#030810",
      bgColor2: "#081828",
      bgGradientAngle: 200,
    },
  },
  {
    key: "c_citrus",
    label: "Citrus",
    thumb: "linear-gradient(160deg,#0d0900,#ffdd00)",
    category: "color",
    config: {
      colorStart: "#ffee44",
      colorEnd: "#ff9900",
      haloColor: "#ffdd00",
      bgType: "gradient",
      bgColor: "#0d0900",
      bgColor2: "#1a1100",
      bgGradientAngle: 170,
    },
  },
  {
    key: "c_champagne",
    label: "Champagne",
    thumb: "linear-gradient(160deg,#100e08,#e8d5a0)",
    category: "color",
    config: {
      colorStart: "#f5e8c0",
      colorEnd: "#d4b870",
      haloColor: "#e8d5a0",
      bgType: "gradient",
      bgColor: "#100e08",
      bgColor2: "#201c10",
      bgGradientAngle: 180,
    },
  },
  {
    key: "c_infrared",
    label: "Infrared",
    thumb: "linear-gradient(160deg,#050000,#ff0066)",
    category: "color",
    config: {
      colorStart: "#ff0044",
      colorEnd: "#ff6600",
      haloColor: "#ff0055",
      bgType: "solid",
      bgColor: "#050000",
    },
  },
];

// Rays/halo structure presets — only affect shape, count, spread, direction, effects
// Colors are left as-is (config is applied on top of current config)
export const RAYS_PRESETS: RaysPreset[] = [
  {
    key: "r_side_glow",
    label: "Side glow",
    thumb:
      "conic-gradient(from 160deg at 110% 0%, transparent 0deg, #aaa 87deg, transparent 87deg)",
    category: "rays",
    config: {
      rayCount: 16,
      rayWidth: 85,
      divergence: 2.15,
      rayLength: 0.75,
      opacity: 0.37,
      blendMode: "screen",
      direction: 217,
      spread: 87,
      originX: 105.59,
      originY: -26.67,
      haloBlendMode: "lighter",
      halo: 0.39,
      haloSize: 0.43,
      haloOriginX: 19.88,
      haloOriginY: 160.64,
      blur: 16,
      noise: 8,
      grainSize: 1,
      randomness: 53,
      seed: 612616,
    },
  },
  {
    key: "r_warm_haze",
    label: "Warm haze",
    thumb:
      "conic-gradient(from 115deg at 20% 0%, transparent 0deg, #aaa 48deg, transparent 48deg)",
    category: "rays",
    config: {
      rayCount: 6,
      rayWidth: 85,
      divergence: 2.65,
      rayLength: 0.6,
      opacity: 0.39,
      blendMode: "screen",
      haloBlendMode: "lighter",
      direction: 161,
      spread: 48,
      originX: 20,
      originY: -23,
      haloOriginX: 30,
      haloOriginY: -20,
      halo: 0.39,
      haloSize: 0.43,
      blur: 16,
      noise: 8,
      grainSize: 1,
      randomness: 50,
      seed: 869010,
      fadeToTransparent: true,
    },
  },
  {
    key: "r_aurora",
    label: "Aurora",
    thumb: "linear-gradient(180deg, #aaa 0%, transparent 60%, #777 100%)",
    category: "rays",
    config: {
      rayCount: 40,
      rayWidth: 120,
      divergence: 1.6,
      rayLength: 1.3,
      opacity: 0.35,
      blur: 22,
      spread: 120,
      direction: 180,
      originX: 50,
      originY: -20,
      halo: 0.25,
      haloSize: 0.5,
      randomness: 50,
      noise: 20,
      blendMode: "screen",
      fadeToTransparent: true,
    },
  },
  {
    key: "r_mist",
    label: "Dense mist",
    thumb: "linear-gradient(180deg, #aaa 0%, transparent 100%)",
    category: "rays",
    config: {
      rayCount: 60,
      rayWidth: 120,
      divergence: 1.4,
      rayLength: 1.5,
      opacity: 0.3,
      blur: 35,
      spread: 140,
      direction: 185,
      originX: 50,
      originY: -10,
      halo: 0.25,
      haloSize: 0.55,
      randomness: 50,
      noise: 15,
      blendMode: "screen",
      fadeToTransparent: true,
    },
  },
  {
    key: "r_fan",
    label: "Fan",
    thumb:
      "conic-gradient(from 120deg at 50% 0%, transparent 0deg, #aaa 60deg, transparent 120deg)",
    category: "rays",
    config: {
      rayCount: 32,
      rayWidth: 55,
      divergence: 1.8,
      rayLength: 1.6,
      opacity: 0.5,
      blur: 12,
      spread: 120,
      direction: 180,
      originX: 50,
      originY: -5,
      halo: 0.55,
      haloSize: 0.22,
      randomness: 25,
      blendMode: "lighter",
    },
  },
  {
    key: "r_burst",
    label: "Burst",
    thumb:
      "conic-gradient(from 0deg at 50% 50%, #aaa 0deg, transparent 20deg, #aaa 40deg, transparent 60deg, #aaa 80deg, transparent 100deg, #aaa 120deg, transparent 140deg, #aaa 160deg, transparent 180deg, #aaa 200deg, transparent 220deg, #aaa 240deg, transparent 260deg, #aaa 280deg, transparent 300deg, #aaa 320deg, transparent 340deg, #aaa 360deg)",
    category: "rays",
    config: {
      rayCount: 80,
      rayWidth: 14,
      divergence: 5,
      rayLength: 0.4,
      opacity: 0.5,
      blendMode: "lighter",
      blur: 21.5,
      spread: 360,
      direction: 90,
      originX: 50,
      originY: 50,
      fadeToTransparent: true,
      randomness: 20,
      seed: 1337,
      noise: 8,
      grainSize: 1,
    },
  },
  {
    key: "r_sidelight",
    label: "Side light",
    thumb:
      "conic-gradient(from 60deg at 0% 40%, transparent 0deg, #aaa 40deg, transparent 80deg)",
    category: "rays",
    config: {
      rayCount: 18,
      rayWidth: 80,
      divergence: 1.5,
      rayLength: 1.6,
      opacity: 0.82,
      blendMode: "lighter",
      blur: 14,
      spread: 50,
      direction: 101,
      originX: -69.121,
      originY: 21.873,
      halo: 0.5,
      haloSize: 0.35,
      haloOriginX: 37.239,
      haloOriginY: 36.782,
      haloBlendMode: "lighter",
      randomness: 30,
      seed: 1337,
      noise: 8,
      grainSize: 1,
    },
  },

  {
    key: "r_canopy",
    label: "Canopy",
    thumb:
      "conic-gradient(from 130deg at 50% 0%, transparent 0deg, #aaa 100deg, transparent 100deg)",
    category: "rays",
    config: {
      rayCount: 22,
      rayWidth: 50,
      divergence: 1.8,
      rayLength: 1.5,
      opacity: 0.5,
      blur: 18,
      spread: 35,
      direction: 195,
      originX: 77.799,
      originY: -132.757,
      randomness: 40,
      seed: 1337,
      blendMode: "screen",
    },
  },
];

export const PRESETS: RaysPreset[] = [...COLOR_PRESETS, ...RAYS_PRESETS];
